apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cip-ingress
spec:
  rules:
    - host: cip.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cip-backend
                port:
                  number: 80
